-- QUERY TO CALCULATE TOTAL SALES PER YEAR
SELECT YEAR_ID , SUM(SALES) AS TOTAL_SALES
FROM SALES_ORDER_ORC
GROUP BY (YEAR_ID) ; 



-- QUERY TO FIND A PRODUCT WHICH WAS ORDERED THE MOST
SELECT PRODUCTLINE , SUM(QUANTITYORDERED) AS TOTAL_UNITS 
FROM SALES_ORDER_ORC
GROUP BY (PRODUCTLINE)
ORDER BY TOTAL_UNITS DESC
LIMIT 1 ;


-- QUERY TO CALCULATE TOTAL SALES FOR EACH QUARTER
SELECT YEAR_ID AS YEAR , QTR_ID AS QUARTER , SUM(SALES) AS TOTAL_SALES
FROM SALES_ORDER_ORC
GROUP BY QTR_ID , YEAR_ID
ORDER BY YEAR ,QUARTER ;


-- QUERY TO CALCULATE MINIMUM SALES FOR A QUARTER
SELECT YEAR_ID AS YEAR , QTR_ID AS QUARTER , SUM(SALES) AS TOTAL_SALES
FROM SALES_ORDER_ORC
GROUP BY QTR_ID , YEAR_ID
ORDER BY TOTAL_SALES LIMIT 1;


--QUERY TO FIND OUT THE COUNTRY WHICH HAD MINIMUM SALE FOR A GIVEN YEAR
WITH COUNTRY_YEAR_SALES AS (
SELECT COUNTRY ,YEAR_ID as YEAR, SUM(SALES) AS TOTAL_SALES
FROM SALES_ORDER_ORC
GROUP BY COUNTRY ,YEAR_ID),
CTE AS (
    SELECT * , ROW_NUMBER() OVER (PARTITION BY YEAR ORDER BY TOTAL_SALES) AS RN
    FROM COUNTRY_YEAR_SALES 
)
SELECT COUNTRY,YEAR,TOTAL_SALES FROM CTE WHERE RN = 1;


--QUERY TO FIND OUT THE COUNTRY WHICH HAD MAXIMUM SALE FOR A GIVEN YEAR
WITH COUNTRY_YEAR_SALES AS (
SELECT COUNTRY ,YEAR_ID as YEAR, SUM(SALES) AS TOTAL_SALES
FROM SALES_ORDER_ORC
GROUP BY COUNTRY ,YEAR_ID),
CTE AS (
    SELECT * , ROW_NUMBER() OVER (PARTITION BY YEAR ORDER BY TOTAL_SALES DESC) AS RN
    FROM COUNTRY_YEAR_SALES 
)
SELECT COUNTRY,YEAR,TOTAL_SALES FROM CTE WHERE RN = 1;


--Query to find out quaterly sales for each city
SELECT CITY , YEAR_ID AS YEAR  , QTR_ID as QUARTER, SUM(SALES) AS TOTAL_SALES
FROM SALES_ORDER_ORC
GROUP BY CITY, YEAR_ID, QTR_ID
ORDER BY CITY , YEAR , QUARTER;


--Query to find Month for each year in which maximum quantities were sold
WITH CTE AS (SELECT YEAR_ID , MONTH_ID , SUM(QUANTITYORDERED) AS TOTAL_QUANTITY
    FROM SALES_ORDER_ORC
    GROUP BY YEAR_ID , MONTH_ID
    ORDER BY YEAR_ID , MONTH_ID),
CTE2 AS (SELECT *,
    ROW_NUMBER() OVER (PARTITION BY YEAR_ID ORDER BY TOTAL_QUANTITY DESC) AS RN
    FROM CTE)
SELECT YEAR_ID , MONTH_ID , TOTAL_QUANTITY 
FROM CTE2 WHERE RN = 1;