CREATE TABLE SALES_ORDER_DATA(
    ORDERNUMBER INT,
    QUANTITYORDERED INT,
    PRICEEACH FLOAT,
    ORDERLINENUMBER INT,
    SALES FLOAT,
    STATUS STRING,
    QTR_ID INT,
    MONTH_ID INT,
    YEAR_ID INT,
    PRODUCTLINE STRING,
    MSRP INT,
    PRODUCTCODE STRING,
    PHONE STRING,
    CITY STRING,
    STATE STRING,
    POSTALCODE STRING,
    COUNTRY STRING,
    TERRITORY STRING,
    CONTACTLASTNAME STRING,
    CONTACTFIRSTNAME STRING,
    DEALSIZE STRING
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
STORED AS TEXTFILE
tblproperties ("skip.header.line.count"="1");